version: 1.0.{build}
platform: x64
branches:
  only:
  - dev
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - mail@pygimli.org
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
build_script:
    - set PATH=C:\msys64\bin;%PATH%
    - C:\msys64\bin\sh --login -c "curl -sL http://install.pygimli.org | bash"
