# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

language: cpp
compiler: clang
os:
    - linux
    - osx

osx_image: xcode7.2b2

install:
    - curl -sL http://install.pygimli.org | bash

notifications:
email:
    recipients:
    - mail@pygimli.org
