# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

language: cpp
compiler: gcc
python: 2.7
os: linux

virtualenv:
    system_site_packages: true
          
before_install:
    # We use apt-get to save time, because travis' free build time limit is 50 min.

    # Travis uses cmake 2.8.7 by default (too old for gimli)
    - sudo add-apt-repository ppa:kalakris/cmake -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository --yes ppa:boost-latest/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake

    # Newer gcc, because 4.6 caused weird assembler bug
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - gcc --version
    - g++ --version

    # Boost 1.55
    - sudo apt-get install -qq libboost-system1.55-dev libboost-thread1.55-dev libboost-python1.55-dev

    # Main build dependencies
    - sudo apt-get install -qq build-essential libcppunit-dev
    - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install -qq python-dev python-numpy; fi
    - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install -qq python3-dev python3-numpy; fi
    - sudo apt-get install -qq libblas-dev liblapack-dev
    - sudo apt-get install -qq libsuitesparse-dev

    # Documentation dependencies
    - sudo apt-get install -qq doxygen doxygen-latex dvipng python-scipy
    - sudo apt-get build-dep -qq python-matplotlib python-sphinx
    - sudo pip install -q -U sphinx numpydoc pybtex sphinxcontrib-programoutput sphinxcontrib-bibtex matplotlib

install:
    # Show Infos
    - uname -a
    - gcc --version
    - python --version
    - cmake --version
    - python -c "import numpy; print(numpy.__version__)"

    # Main build
    - mkdir trunk
    - shopt -s extglob
    - mv !(trunk) trunk # necessary because of lib and thirdParty backcopying
    - mkdir build
    - cd build
    - cmake ../trunk
    - make -j 4 gimli
    - make pygimli J=3
      
script:
    # Test gimli
    - make check
    - ./bin/gimliUnitTest

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    # Test pygimli
    - export PYTHONPATH=$PYTHONPATH:`pwd`/../trunk/python
    - python -c "import pygimli; print(pygimli.__version__)"
    - make doc 

notifications:
    email:
        - wagnerfl@student.ethz.ch
        - carsten@resistivity.net
        - thomas@resistivity.net
