name: pgdev
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - pgcore >= 1.4.0
  - matplotlib
  - jupyter
  - sphinx >= 3.1
  - pytest
  - numpy
  - scipy
  - pytest-cov
  - pytest-html
  - sphinx-gallery
  - sphinxcontrib-bibtex
  - sphinxcontrib-programoutput
  - sphinxcontrib-spelling
  - sphinxcontrib-doxylink
  - bibtexparser
  - pyvista>=0.34
  - panel
  - meshio
  - tetgen
  - scooby
  - sphinx-design
  - pydata-sphinx-theme

